### ISSUE TITLE
AtRule without body

### ISSUE THREAD

**Issue by shellscape** [Crunch/postcss-less#3]
Requesting a small improvement to the `AtRule` type. When parsing `@rule();` or `@rule;` it would be great to have a convenience property shared with regular `Rule` types; `node.ruleWithoutBody`. Presently we're having to frequently use:

`(node.type === 'atrule' && (!node.nodes || (node.nodes && node.nodes.length === 0)))`

which works, but it gets messy. Any chance of adding that property to `AtRule` nodes as well?

**Comment by shellscape** [comment]
Crap. I just commented on the wrong repo. Apologies!

**Comment by matthew-dean** [comment]
No problem! ^_^
